Get http://localhost:3000/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhemFrIiwicGFzc3dvcmQiOiI5OTk5IiwibmFtZSI6Ik11aGFtbWFkIFJhemFrIiwiZW1haWwiOiJyYXpha0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMTE2NjYsImV4cCI6MTY4MTExNTI2Nn0.sYLgt9vN8MfXjwAKa6vbd9yuXRZK3OBDaiTvqGRosJA

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "Razak",
    "password": "9999",
    "name": "Muhammad Razak",
    "email": "razak@gmail.com"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Razak",
    "password": "9999"
}